#!/usr/bin/env bash
# SetUp Process for Nginx on a server

apt-get -y update
pat-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx restart
