#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string `Ceci n'est pas une page`

sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_error_page="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen 80 default_server;|$new_error_page|" /etc/nginx/sites-enabled/default

sudo service nginx restart
